---
- name: Create Samba service account groups
  ansible.builtin.group:
    name: "{{ item }}"
    system: true
    state: present
  loop: "{{ samba_system_users }}"

- name: Create Samba service accounts
  ansible.builtin.user:
    name: "{{ item }}"
    group: "{{ item }}"
    system: true
    create_home: false
    shell: /usr/sbin/nologin
    state: present
  loop: "{{ samba_system_users }}"
