---
- name: Start NZBget
  block:
    - name: Create NZBget Directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - "{{ nzbget_data_directory }}"

    - name: NZBGet
      community.docker.docker_container:
        name: "{{ nzbget_container_name }}"
        image: "{{ nzbget_image_name }}:{{ nzbget_image_version }}"
        pull: true
        volumes:
          - "{{ nzbget_download_directory }}:/downloads:rw"
          - "{{ nzbget_data_directory }}:/config:rw"
        ports:
          - "{{ nzbget_port }}:6789"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ nzbget_user_id }}"
          PGID: "{{ nzbget_group_id }}"
        restart_policy: unless-stopped
        memory: "{{ nzbget_memory }}"
        labels:
          traefik.enable: "{{ nzbget_available_externally | string }}"
          traefik.http.routers.nzbget.rule: "Host(`{{ nzbget_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.nzbget.tls.certresolver: "letsencrypt"
          traefik.http.routers.nzbget.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.nzbget.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.nzbget.loadbalancer.server.port: "6789"
          homepage.group: Download Tools
          homepage.name: Nzbget
          homepage.icon: nzbget.png
          homepage.href: "https://nzbget.{{ hostvars[inventory_hostname]['ansible_nas_domain'] }}"
          homepage.description: Nzbget
          homepage.widget.type: nzbget
          homepage.widget.url: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{ nzbget_port }}"
          homepage.widget.username: "{{ lookup('ansible.builtin.env', 'NZBGET_USERNAME') }}"
          homepage.widget.password: "{{ lookup('ansible.builtin.env', 'NZBGET_PASSWORD') }}"
  when: nzbget_enabled is true

- name: Stop NZBget
  block:
    - name: Stop NZBget
      community.docker.docker_container:
        name: "{{ nzbget_container_name }}"
        state: absent
  when: nzbget_enabled is false
